Update kubeplugin

diff --git a/scripts/kubeplugin b/scripts/kubeplugin
--- a/scripts/kubeplugin
+++ b/scripts/kubeplugin
@@ -1,1 +1,36 @@
+#!/bin/bash
 
+# Перевірка кількості аргументів
+if [ "$#" -ne 2 ]; then
+    echo "Usage: $0 <node|pod> <namespace>"
+    exit 1
+fi
+
+# Отримання аргументів
+RESOURCE_TYPE=$1
+NAMESPACE=$2
+
+# Перевірка валідності типу ресурсу
+if [[ "$RESOURCE_TYPE" != "pod" && "$RESOURCE_TYPE" != "node" ]]; then
+    echo "Error: Invalid resource type. Use 'pod' or 'node'."
+    exit 1
+fi
+
+# Отримання статистики
+if [ "$RESOURCE_TYPE" == "pod" ]; then
+    kubectl top pods -n "$NAMESPACE" | tail -n +2 | while read -r line
+    do
+        NAME=$(echo "$line" | awk '{print $1}')
+        CPU=$(echo "$line" | awk '{print $2}')
+        MEMORY=$(echo "$line" | awk '{print $3}')
+        echo "$RESOURCE_TYPE, $NAMESPACE, $NAME, $CPU, $MEMORY"
+    done
+elif [ "$RESOURCE_TYPE" == "node" ]; then
+    kubectl top nodes | tail -n +2 | while read -r line
+    do
+        NAME=$(echo "$line" | awk '{print $1}')
+        CPU=$(echo "$line" | awk '{print $2}')
+        MEMORY=$(echo "$line" | awk '{print $3}')
+        echo "$RESOURCE_TYPE, $NAMESPACE, $NAME, $CPU, $MEMORY"
+    done
+fi
